### ISSUE TITLE
Crash when using adding section headers

### ISSUE THREAD

**Issue by rtsao** [lukescott/DraggableCollectionView#11]
I am running the FlowLayoutDemo, but when I try adding section headers and pick up a cell to move, I get a crash as soon as I release the item or drag it over another.

```
2013-07-22 12:14:04.596 FlowLayoutDemo[99484:c07] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: <_UICollectionViewItemKey: 0xdc82d70> Type = SV Kind = UICollectionElementKindSectionHeader IndexPath = <NSIndexPath 0xdc82c20> 2 indexes [0, 0])'
```

**Comment by lukescott** [comment]
Can you provide the backtrace? Screenshot will do.

**Comment by rtsao** [comment]
![screen shot 2013-07-22 at 3 04 40 pm](https://f.cloud.github.com/assets/780408/838276/c983bdb2-f31a-11e2-9ea6-09ae94076dd1.png)

**Comment by lukescott** [comment]
You're missing your `collectionView:viewForSupplementaryElementOfKind:atIndexPath:` delegate call, or you're not returning a view for `UICollectionElementKindSectionHeader` in it. If you do have one and the code looks right, check to make sure the Storyboard has the same `Identifier` applied and the storyboard is saved. Might have to do a Build -> Clean.

**Comment by rtsao** [comment]
Thanks, that seems to have fixed my problem!
