### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by visualication** [lukescott/DraggableCollectionView#8]
Hi,
thx for your work. but i dont't get it run :(

I have a collection view with only one section, so my datasource is an array with "pages" objects. when a drag a cell to a new position, the animation is ok and the other cells are moving corractly. when i drop the cell, the cell that is now on the position of the dragged cell, returns to the content of the dragged cell.

in short: if i have two cells wih different content, after dragging both are with equal content.

what do i wrong?

thx
thorsten

**Comment by visualication** [comment]
ok, i found the problem: after moving i had called [collectionView reloadData]. after deleting this call the moving works fine :-)

**Comment by lukescott** [comment]
The reload/insert/move/delete functions are used when the data source has changed, but the `UICollectionView` doesn't know it. You only used `reloadData` when your data has completely changed. `reloadItemsAtIndexPaths` could be used if the cell class has changed.

In the case of the user dragging, the `UICollectionView` knows this, and lets you know to update your datasource. So you don't have to do anything else.
